version: "3.8"

services:
  web:
    image: wordpress:6.4-php8.2-apache
    container_name: mc-wp
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: mappingcrimes
    volumes:
      - ../wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mc-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mappingcrimes
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: